-- GENERATED by theme/render.sh from theme/palette.sh -- do not edit by hand.
-- Gruvbox Material (dark / medium / material)
return {
    bg_dim = "1b1b1b", bg0 = "282828", bg1 = "32302f", bg2 = "32302f",
    bg3    = "45403d",    bg4 = "45403d", bg5 = "5a524c",
    fg0    = "d4be98",    fg1 = "ddc7a1",
    grey0  = "7c6f64",  grey1 = "928374", grey2 = "a89984",
    red    = "ea6962",    orange = "e78a4e", yellow = "d8a657",
    green  = "a9b665",  aqua   = "89b482",   blue   = "7daea3",
    purple = "d3869b",
}
