-- GENERATED by theme/render.sh -- do not edit by hand. Edit theme/templates/.
-- Theme: Gruvbox Material · Dark · Hard · Material, accent #a9b665
return {
    bg_dim = "141617", bg0 = "1d2021", bg1 = "282828", bg2 = "282828",
    bg3    = "3c3836",    bg4 = "3c3836", bg5 = "504945",
    fg0    = "d4be98",    fg1 = "ddc7a1",
    grey0  = "7c6f64",  grey1 = "928374", grey2 = "a89984",
    red    = "ea6962",    orange = "e78a4e", yellow = "d8a657",
    green  = "a9b665",  aqua   = "89b482",   blue   = "7daea3",
    purple = "d3869b",
    -- derived by theme/lib.sh
    accent = "a9b665", accent_fg = "1d2021", shadow = "141617",
}
