
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


-- Gruvbox Material palette, generated by this repo's theme/render.sh
local c = require("colors")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = terminal .. " -e yazi"   -- TUI, needs a terminal
local scripts     = os.getenv("HOME") .. "/.config/hypr/scripts"
local menu        = scripts .. "/rofi-launch.sh"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
hl.on("hyprland.start", function ()
    -- hyprpm's "enabled" state doesn't auto-inject into a fresh Hyprland
    -- process on boot -- it has to be reloaded every session, chained with a
    -- config reload so hy3 actually takes effect instead of silently falling
    -- back to whatever `general.layout` resolves to without it loaded.
    hl.exec_cmd("hyprpm reload -n && hyprctl reload")

    -- Polkit agent: enabled via systemd (install.sh), not started here.
    -- The shipped unit is WantedBy=graphical-session.target, which survives
    -- `hyprctl reload` -- this hl.on block does not re-fire on reload, so an
    -- exec_cmd here would only ever run once per login anyway.
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")   -- notification daemon + control centre
    -- Clipboard history; the picker is SUPER+SHIFT+V.
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
-- Qt has no theming of its own outside a DE; without this it falls back to a
-- stock style ignoring every colour we set elsewhere. qt6ct's scheme is
-- generated from the same palette (theme/render.sh) as everything else.
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 2,
        gaps_out = 4,

        border_size = 2,

        col = {
            active_border   = "rgba(" .. c.green .. "ee)",
            inactive_border = "rgba(" .. c.bg3 .. "aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "hy3",
    },

    -- hy3's own tab-group theming (SUPER+W to group/ungroup, [ ] to cycle
    -- tabs, SUPER+SHIFT+W to lock). hy3 has its own tab bar, entirely
    -- separate from Hyprland's native `group`/`groupbar` config above (which
    -- is now unused, since nothing triggers native grouping with hy3 active).
    -- Green is the primary accent; locked tabs get their own red so a locked
    -- group stays visually distinct rather than just looking like any other
    -- active tab.
    plugin = {
        hy3 = {
            tabs = {
                colors = {
                    active        = "rgba(" .. c.green .. "ee)",
                    active_border = "rgba(" .. c.green .. "ee)",
                    active_text   = "rgba(" .. c.bg0 .. "ff)",

                    focused        = "rgba(" .. c.green .. "ee)",
                    focused_border = "rgba(" .. c.green .. "ee)",
                    focused_text   = "rgba(" .. c.bg0 .. "ff)",

                    inactive        = "rgba(" .. c.bg3 .. "aa)",
                    inactive_border = "rgba(" .. c.bg3 .. "aa)",
                    inactive_text   = "rgba(" .. c.fg1 .. "ff)",

                    locked        = "rgba(" .. c.red .. "ee)",
                    locked_border = "rgba(" .. c.red .. "ee)",
                    locked_text   = "rgba(" .. c.bg0 .. "ff)",
                },
            },
        },
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = tonumber("ee" .. c.bg_dim, 16),
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        -- No wallpaper daemon: Hyprland paints the root surface itself, so the
        -- background is one palette colour and stays in sync with everything else.
        -- Both of these must be off or the built-in mascot covers it.
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        background_color        = tonumber("ff" .. c.bg0, 16),
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        -- us,ara matches what localectl already reports for X11.
        kb_layout  = "us,ara",
        kb_variant = ",",
        kb_model   = "",
        -- SUPER+space cycles the layouts. Done as an xkb option rather than a
        -- hl.bind so the switch happens inside xkb itself: Hyprland then emits
        -- the activelayout event that waybar's language module listens for.
        kb_options = "grp:win_space_toggle",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal), { description = "Terminal" })
local closeWindowBind = hl.bind(mainMod .. " + X", hl.dsp.window.close(), { description = "Close window" })
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + SHIFT + X", hl.dsp.window.kill(), { description = "Force close window" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager), { description = "File manager (yazi)" })
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(scripts .. "/rofi-clipboard.sh"), { description = "Clipboard history" })
-- Fullscreen covers the whole output; maximized keeps the bar and gaps.
-- Plain F is maximize, not fullscreen -- it's the one used more often.
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen({ mode = "maximized" }), { description = "Maximize" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }), { description = "Fullscreen" })
hl.bind(mainMod .. " + SHIFT + Space", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })

-- Window groups (tabs), hy3's own tab-group system -- not Hyprland's native
-- groups, which hy3's tree doesn't participate in. bracketleft/right, like
-- "slash" above, is the X11 keysym name -- Hyprland's Lua binds take keysym
-- names, not literal chars.
hl.bind(mainMod .. " + W",         hl.plugin.hy3.make_group("tab", { toggle = true }), { description = "Tab-group/ungroup window" })
hl.bind(mainMod .. " + SHIFT + W", hl.plugin.hy3.lock_tab(), { description = "Lock tab group" })
hl.bind(mainMod .. " + bracketleft",  hl.plugin.hy3.focus_tab({ direction = "l" }), { description = "Previous tab" })
hl.bind(mainMod .. " + bracketright", hl.plugin.hy3.focus_tab({ direction = "r" }), { description = "Next tab" })
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu), { description = "App launcher" })

-- Window switcher: one menu, Alt+a toggles this-workspace/all-workspaces
-- inside it instead of a separate SHIFT+Tab bind.
hl.bind(mainMod .. " + Tab", hl.dsp.exec_cmd(scripts .. "/rofi-windows.sh"), { description = "Windows" })

-- Power menu and notification centre.
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd(scripts .. "/rofi-power.sh"), { description = "Power menu" })
hl.bind(mainMod .. " + N",      hl.dsp.exec_cmd("swaync-client -t -sw"), { description = "Notification centre" })
hl.bind("Print", hl.dsp.exec_cmd(scripts .. "/rofi-screenshot.sh"), { description = "Screenshot menu" })
hl.bind(mainMod .. " + SHIFT + slash", hl.dsp.exec_cmd(scripts .. "/rofi-help.sh"), { description = "This cheat sheet" })
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo(), { description = "Pseudo-tile" })
-- hy3 has no dedicated "toggle split direction" dispatcher; change_group's
-- "opposite" action flips the current group between h/v, which is the same
-- thing.
hl.bind(mainMod .. " + T", hl.plugin.hy3.change_group("opposite"), { description = "Toggle split direction" })
hl.bind(mainMod .. " + V", hl.plugin.hy3.change_group("v"), { description = "Split vertical" })
hl.bind(mainMod .. " + C", hl.plugin.hy3.change_group("h"), { description = "Split horizontal" })

-- Move focus with mainMod + arrow keys, or vim-style hjkl -- both call the
-- same hy3 dispatcher, so either habit works identically.
hl.bind(mainMod .. " + left",  hl.plugin.hy3.move_focus("l"), { description = "Focus left" })
hl.bind(mainMod .. " + right", hl.plugin.hy3.move_focus("r"), { description = "Focus right" })
hl.bind(mainMod .. " + up",    hl.plugin.hy3.move_focus("u"), { description = "Focus up" })
hl.bind(mainMod .. " + down",  hl.plugin.hy3.move_focus("d"), { description = "Focus down" })
hl.bind(mainMod .. " + H", hl.plugin.hy3.move_focus("l"), { description = "Focus left" })
hl.bind(mainMod .. " + L", hl.plugin.hy3.move_focus("r"), { description = "Focus right" })
hl.bind(mainMod .. " + K", hl.plugin.hy3.move_focus("u"), { description = "Focus up" })
hl.bind(mainMod .. " + J", hl.plugin.hy3.move_focus("d"), { description = "Focus down" })

-- Move the focused window through the tree with mainMod + SHIFT + direction,
-- arrows or hjkl. `once` moves it exactly one step instead of hy3's default
-- of repeatedly re-parenting until it can't move any further.
hl.bind(mainMod .. " + SHIFT + left",  hl.plugin.hy3.move_window("l", { once = true }), { description = "Move window left" })
hl.bind(mainMod .. " + SHIFT + right", hl.plugin.hy3.move_window("r", { once = true }), { description = "Move window right" })
hl.bind(mainMod .. " + SHIFT + up",    hl.plugin.hy3.move_window("u", { once = true }), { description = "Move window up" })
hl.bind(mainMod .. " + SHIFT + down",  hl.plugin.hy3.move_window("d", { once = true }), { description = "Move window down" })
hl.bind(mainMod .. " + SHIFT + H", hl.plugin.hy3.move_window("l", { once = true }), { description = "Move window left" })
hl.bind(mainMod .. " + SHIFT + L", hl.plugin.hy3.move_window("r", { once = true }), { description = "Move window right" })
hl.bind(mainMod .. " + SHIFT + K", hl.plugin.hy3.move_window("u", { once = true }), { description = "Move window up" })
hl.bind(mainMod .. " + SHIFT + J", hl.plugin.hy3.move_window("d", { once = true }), { description = "Move window down" })

-- Raise focus to the parent group / lower it back into the child -- hy3's
-- equivalent of i3's "focus parent".
hl.bind(mainMod .. " + A",         hl.plugin.hy3.change_focus("raise"), { description = "Focus parent (raise)" })
hl.bind(mainMod .. " + SHIFT + A", hl.plugin.hy3.change_focus("lower"), { description = "Focus child (lower)" })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + Q",         hl.dsp.workspace.toggle_special("magic"), { description = "Scratchpad" })
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.move({ workspace = "special:magic" }), { description = "Move to scratchpad" })

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { description = "Volume up", locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { description = "Volume down", locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { description = "Mute output", locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { description = "Mute microphone", locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { description = "Brightness up", locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { description = "Brightness down", locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { description = "Next track", locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { description = "Play / pause", locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { description = "Play / pause", locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { description = "Previous track", locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- rofi's own layer fades/scales in by default, which reads as lag before a
-- screenshot mode is even picked -- killing rofi's own animation makes the
-- menu appear instantly instead.
hl.layer_rule({
    name  = "no-anim-rofi",
    match = { namespace = "^rofi$" },
    no_anim = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Windows launched from the waybar status modules: float them, centred.
hl.window_rule({
    name  = "float-settings",
    match = { class = "^(net-tui|pavucontrol|\\.blueman-manager-wrapped|blueman-manager)$" },
    float = true,
    size  = "900 600",
    move  = "cursor -450 -300",
})
