-- GENERATED by theme/render.sh -- do not edit by hand. Edit theme/templates/.
-- Theme: ${THEME_LABEL}, accent #${ACCENT}
return {
    bg_dim = "${BG_DIM}", bg0 = "${BG0}", bg1 = "${BG1}", bg2 = "${BG2}",
    bg3    = "${BG3}",    bg4 = "${BG4}", bg5 = "${BG5}",
    fg0    = "${FG0}",    fg1 = "${FG1}",
    grey0  = "${GREY0}",  grey1 = "${GREY1}", grey2 = "${GREY2}",
    red    = "${RED}",    orange = "${ORANGE}", yellow = "${YELLOW}",
    green  = "${GREEN}",  aqua   = "${AQUA}",   blue   = "${BLUE}",
    purple = "${PURPLE}",
    -- derived by theme/lib.sh
    accent = "${ACCENT}", accent_fg = "${ACCENT_FG}", shadow = "${SHADOW}",
}
