[Appearance]
color_scheme_path=${HOME}/.config/qt6ct/colors/gruvbox-material.conf
custom_palette=true
icon_theme=Gruvbox-Plus-Dark
standard_dialogs=default
style=Fusion

[Fonts]
general="Roboto,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
fixed="JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
